services:
  db:
    container_name: app-vendas
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_vendas
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    
    ports:
      - "5437:5432"